# Configuration file location: $HOME/.config/acme-lsp/config.toml

# gopls setup from: https://github.com/9fans/acme-lsp
# ccls setup from: https://9lab.org/9port/acme-with-lsp/

ProxyNetwork = "unix"
ProxyAddress = "/tmp/ns.utt.:0/acme-lsp.rpc"
AcmeNetwork = "unix"
AcmeAddress = "/tmp/ns.utt.:0/acme"
RootDirectory = "/"
HideDiagnostics = true
FormatOnPut = false
RPCTrace = false
CodeActionsOnPut = ["source.organizeImports"]

WorkspaceDirectories = []

[Servers]

[Servers.gopls]
Command = ["gopls", "serve", "-rpc.trace"]
StderrFile = "/Users/utt/Library/Logs/gopls.stderr.log"
LogFile = "/Users/utt/Library/Logs/gopls.log"

# These settings gets passed to gopls
[Servers.gopls.Options]
hoverKind = "FullDocumentation"

# These settings gets passed to gopls on format.
# Gopls ignores these, but other LSP servers recognize
# them.
[Servers.gopls.FormattingOptions]
# Size of a tab in spaces.
TabSize = 0
# Prefer spaces over tabs.
InsertSpaces = false
# Trim trailing whitespace on a line.
TrimTrailingWhitespace = true
# Insert a newline character at the end of the file
# if one does not exist.
InsertFinalNewline = true
# Trim all newlines after the final newline at the
# end of the file.
TrimFinalNewlines = true

[Servers.ccls]
Command = [
  "ccls",
  "-log-file=/Users/utt/Library/Logs/ccls.log.log",
  "-v=4",
  # clang.extraArgs from 'clang -v -fsyntax-only -x c++ /dev/null'
  # clang.resourceDir from 'clang -print-resource-dir'
  "--init={\"cache\":{\"directory\":\"/Users/utt/.cache/ccls\"},\"highlight\":{\"enabled\":true},\"clang\": {\"extraArgs\": [\"-DOSX\", \"-D_THREAD_SAFE\", \"-DPLAN9\", \"-D__plan9__\", \"-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1\",\"-I/Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include\",\"-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include\",\"-I/Library/Developer/CommandLineTools/usr/include\",\"-I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks\", \"-I/Users/utt/plan9port/include\", \"-I/opt/homebrew/lib\", \"-lSDL2\", \"-lSDL2_ttf\"], \"resourceDir\": \"/Library/Developer/CommandLineTools/usr/lib/clang/15.0.0\"},\"completion\":{\"detailedLabel\":false}}",
]
StderrFile = "/Users/utt/Library/Logs/ccls.stderr.log"
LogFile = "/Users/utt/Library/Logs/ccls.log"

# to enable pylsp, install projects either as is or as editable for $HOME/venv (using $HOME/venv as central user python3 management):
# $HOME/venv/bin/python -m pip install -e <path to project>
# $HOME/venv/bin/python -m pip install <path to project>
[Servers.pylsp]
Command = ["pylsp"]
StderrFile = "/Users/utt/Library/Logs/pylsp.stderr.log"
LogFile = "/Users/utt/Library/Logs/pylsp.log"

[[FilenameHandlers]]
Pattern = "[/\\\\]go\\.mod$"
LanguageID = "go.mod"
ServerKey = "gopls"

[[FilenameHandlers]]
Pattern = "[/\\\\]go\\.sum$"
LanguageID = "go.sum"
ServerKey = "gopls"

[[FilenameHandlers]]
Pattern = "\\.go$"
# Don't run this LSP in files in /projects/example (for instance because that
# project needs a gopls with a Bazel packages driver).
Ignore = "/projects/example"
LanguageID = "go"
ServerKey = "gopls"

[[FilenameHandlers]]
Pattern = "\\.(c|h)$"
LanguageID = "c"
ServerKey = "ccls"

[[FilenameHandlers]]
Pattern = "\\.(cpp|cc|hpp|hh)$"
LanguageID = "cpp"
ServerKey = "ccls"

[[FilenameHandlers]]
Pattern = "\\.pyi?$"
ServerKey = "pylsp"
