# Configuration file location: /home/utt/.config/acme-lsp/config.toml

ProxyNetwork = "unix"
ProxyAddress = "/tmp/ns.utt.:0/acme-lsp.rpc"
AcmeNetwork = "unix"
AcmeAddress = "/tmp/ns.utt.:0/acme"
RootDirectory = "/"
HideDiagnostics = true
FormatOnPut = true
RPCTrace = false


WorkspaceDirectories = [
]

[Servers]
	[Servers.gopls]
	Command = ["gopls", "serve", "-rpc.trace"]
	StderrFile = "gopls.stderr.log"
	LogFile = "gopls.log"

		# These settings gets passed to gopls
		[Servers.gopls.Options]
		hoverKind = "FullDocumentation"

	[Servers.ccls]
# if ccls doesn't work, try to
# * add -I -D etc to .ccls file as well as to clang.extraArgs
# * add project path to WorkspaceDirectories
# don't know why it's like that, my guess is it's something to do with compilation
# as I didn't encounter this issue with non-pre-processor c files.
	Command = [
		# "ccls",
		"ccls",
		"-v=2",

		# clang.extraArgs from 'clang -v -fsyntax-only -x c++ /dev/null'
		# clang.resourceDir from 'clang -print-resource-dir'
		"--init={\"cache\":{\"directory\":\"$HOME/.cache/ccls\"},\"highlight\":{\"enabled\":true},\"clang\": {\"extraArgs\": [\"-internal-isystem\", \"/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1\", \"-internal-isystem\", \"/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include\", \"-internal-isystem\", \"/Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include\", \"-internal-externc-isystem\", \"/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include\", \"-internal-externc-isystem\", \"/Library/Developer/CommandLineTools/usr/include\"], \"resourceDir\": \"/Library/Developer/CommandLineTools/usr/lib/clang/15.0.0\"},\"completion\":{\"detailedLabel\":false}}"
	]
	StderrFile = "ccls.stderr.log"
	LogFile = "ccls.log"

[[FilenameHandlers]]
Pattern = '([/\\]go\.mod)|([/\\]go\.sum)|(\.go)$'
ServerKey = "gopls"

[[FilenameHandlers]]
Pattern = '(\.h)|(\.c)|(\.cpp)|(\.cc)|(\.def)$'
ServerKey = "ccls"
